#!/usr/bin/env bash
# Script to Install and configure HAproxy on a server.

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get install haproxy=2.4.\* -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

HAProxyConfig="
backend web_servers
    balance roundrobin
    server web-01 34.139.205.239:80 check
    server web-02 44.200.28.42:80 check
    
frontend lb
    bind *:80
    default_backend web_servers
"

echo "$HAProxyConfig" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
